export const channels = {
  chooseLibraryFolder: "library:choose-folder",
  listLibraryRoots: "library:list-roots",
  scanLibrary: "library:scan",
  cancelScan: "library:cancel-scan",
  getLatestScanJob: "library:latest-scan-job",
  listAlbums: "library:list-albums",
  listScanErrors: "library:list-scan-errors",
  previewAlbumTitleEdit: "tagging:preview-album-title",
  applyAlbumTitleEdit: "tagging:apply-album-title",
  createSyncProfile: "sync:choose-target-create-profile",
  planSync: "sync:plan",
  applySync: "sync:apply",
  jobProgress: "jobs:progress",
  scanJobUpdated: "jobs:scan-updated",
} as const;
