export const channels = {
  chooseLibraryFolder: "library:choose-folder",
  listLibraryRoots: "library:list-roots",
  scanLibrary: "library:scan",
  cancelScan: "library:cancel-scan",
  getLatestScanJob: "library:latest-scan-job",
  createDatabaseBackup: "database:create-backup",
  chooseDatabaseRestore: "database:choose-restore",
  applyDatabaseRestore: "database:apply-restore",
  queryLibrary: "library:query",
  previewAlbumTitleEdit: "tagging:preview-album-title",
  applyAlbumTitleEdit: "tagging:apply-album-title",
  createSyncProfile: "sync:choose-target-create-profile",
  planSync: "sync:plan",
  applySync: "sync:apply",
  jobProgress: "jobs:progress",
  scanJobUpdated: "jobs:scan-updated",
} as const;
